name: Flutter CI

on:
  push:
    branches:
      - '**'        # matches every branch

jobs:
  android-integration_tests:
    name: Android Integration Tests
    runs-on: macos-latest
    env:
      GOOGLE_MAP_API_KEY: ${{ secrets.GOOGLE_MAP_API_KEY }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      #Setup Flutter Environnement
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: run tests
        timeout-minutes: 30
        uses: reactivecircus/android-emulator-runner@v2
        with:
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          api-level: 29
          profile: "pixel"
          script: flutter test integration_test --verbose 